<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package AMP for Magento 2
*/
?>
<?php
/**
 * @var $block \Amasty\Amp\Block\Page\Html\Header\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
?>

<amp-accordion class="amamp-navigation" animate disable-session-states>
    <?= /* @noEscape */ $block->getMenuHtml('level-top', 'submenu') ?>
</amp-accordion>
