<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package FAQ and Product Questions for Magento 2
*/
?>
<?php /** @var \Amasty\Faq\Block\Widgets\SearchBox $block */ ?>
<div class="am-search-box-wrapper">
    <div class="<?= $block->escapeHtml($block->getSearchBoxAlign()) ?>"
         style="width: <?= $block->escapeHtml($block->getSearchBoxWidth()) ?>">
        <?= /** @noEscape */ $block->getSearchBlockHtml() ?>
    </div>
</div>
