<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package FAQ and Product Questions for Magento 2
*/
?>
<?php
/** @var \Amasty\Faq\Block\RichData\StructuredData $block */
if (!empty($block->getStructuredData())): ?>
    <script type="application/ld+json">
        <?= /* @noEscape */ \Zend_Json::encode($block->getStructuredData()); ?>
    </script>
<?php endif; ?>
