<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package AJAX Shopping Cart for Magento 2
*/
?>
<script>
    require([
        'jquery',
        'jquery/colorpicker/js/colorpicker'
    ], function ($) {
        $(document).ready(function () {
            $('input[id*="amasty_cart_visual"]').not('input[id*="_inherit"]').each(function (i, element) {
                var $element = $(element),
                    value = $element.val();
                $element.css("backgroundColor", "#" + value);

                // Attach the color picker
                $element.ColorPicker({
                    color: value,
                    onChange: function (hsb, hex, rgb) {
                        $element.css("backgroundColor", "#" + hex).val(hex);
                    }
                });
            });
        });
    });
</script>
