<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package AJAX Shopping Cart for Magento 2
*/
?>
<?php
    /** @var \Amasty\Cart\Block\Config  $block */
    $helper = $block->getHelper();
    $amcartParams = $helper->jsParam($block);
?>
<?php if ($block->isAjaxAdd()): ?>
    <script type="text/x-magento-init">
    <?= /* @noEscape */
        $helper->encode(
            [
                "#product_addtocart_form:not([amcart-observed]), form[data-role=\"tocart-form\"]:not([amcart-observed]), .action.tocart:not([amcart-observed])" => [
                    'Amasty_Cart/js/amcart' => $amcartParams
                ]
            ]
        );
    ?>
    </script>

    <?php if ($helper->isRequestQuoteEnabled()): ?>
        <?php $amcartQuoteParams = $helper->jsParamsForQuote($block); ?>
        <script type="text/x-magento-init">
            <?= /* @noEscape */
                $helper->encode(
                    [
                        ".amquote-addto-button:not([amcart-observed])" => [
                            'Amasty_Cart/js/amcart' => $amcartQuoteParams
                        ]
                    ]
                );
            ?>
        </script>
    <?php endif; ?>
<?php endif; ?>
