<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package AJAX Shopping Cart for Magento 2
*/
?>
<?php
/** @var \Amasty\Cart\Block\Config  $block */
/** @var $escaper \Magento\Framework\Escaper */

$helper = $block->getHelper();

//Visual Options
$backgroundColor = $helper->getBackgroundColor();
$productNameColor = $helper->getProductNameColor();
$textColor = $helper->getTextColor();
$buttonTextColor = $helper->getButtonTextColor();
$leftButtonColor = $helper->getLeftButtonColor();
$rightButtonColor = $helper->getRightButtonColor();
?>

<style>
    <?php if ($backgroundColor): ?>
    #confirmBox,
    .am-related-title > .am-title {
        background-color: #<?= $escaper->escapeHtml($backgroundColor); ?>;
    }
    <?php endif; ?>

    <?php if ($productNameColor): ?>
    #confirmBox a,
    #confirmBox a:hover,
    #confirmBox a:active,
    #confirmBox .amrelated-confirm-header {
        color: #<?= $escaper->escapeHtml($productNameColor); ?>;
    }
    <?php endif;?>

    <?php if ($buttonTextColor): ?>
    .amcart-confirm-buttons .button {
        color: #<?= $escaper->escapeHtml($buttonTextColor); ?>;
    }
    <?php endif;?>

    <?php if ($leftButtonColor): ?>
    .amcart-confirm-buttons .am-btn-left {
        background-color: #<?= $escaper->escapeHtml($leftButtonColor); ?>;
    }
    <?php endif;?>

    <?php if ($rightButtonColor): ?>
    .amcart-confirm-buttons .am-btn-right {
        background-color: #<?= $escaper->escapeHtml($rightButtonColor); ?>;
    }
    <?php endif;?>

    <?php if ($textColor): ?>
    .amcart-confirm-buttons,
    .amcart-confirm-buttons .checkout,
    .amcart-confirm-buttons .checkout:hover,
    .amcart-confirm-buttons .checkout:active,
    .amcart-message-box,
    .am-related-box,
    #am-a-count,
    #am-a-count:visited,
    .am-related-title > .am-title {
        color: #<?= $escaper->escapeHtml($textColor); ?>;
    }
    <?php endif;?>
</style>
