<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package AMP for Magento 2
*/
?>
<?php
/**
 * @var $block \Magento\Theme\Block\Html\Title
 */

$specialAttr = $block->getAddBaseAttributeAria() ? 'aria-labelledby="' . $block->getAddBaseAttributeAria() . '"' : '';
$title = trim($block->getPageHeading()) ? $block->getPageHeading() : '';
?>

<?php if ($title): ?>
    <h1 class="amamp-title" <?= /* @noEscape */ $specialAttr ?>>
        <?= $block->escapeHtml($title) ?>
    </h1>
<?php endif; ?>
