<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Promo Banners Base for Magento 2
*/
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Amasty\PromoBanners\ViewModel\BannersDataProvider $dataProvider */
$dataProvider = $block->getData('ampromoBannersDataProvider');
$banners = $dataProvider->getBanners();
?>

<script type="text/x-magento-init">
    <?= /* @noEscape */ \Zend_Json::encode(['*' => ['Amasty_PromoBanners/js/loader' => $banners]]) ?>
</script>
