<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Store Pickup with Locator for Magento 2
*/
?>
<?php
/** @var \Amasty\StorePickupWithLocator\ViewModel\Location\CurbsideLabel $viewModel */
/** @var \Amasty\Storelocator\Block\View\Location $block */
$location = $block->getCurrentLocation();
$viewModel = $block->getViewModel();
?>

<?php if ($viewModel && $location): ?>
    <?= $viewModel->getCurbsideLabelHtml($location) ?>
<?php endif; ?>
