<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "amreindex-status-checker": {
                            "component": "Amasty_Reindex/js/status-checker",
                            "url": "<?= $block->escapeUrl($block->getUrl('amreindex/reindex/status')); ?>"
                        }
                    }
                }
            }
        }
</script>
