<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Store Pickup with Locator for Magento 2
*/
?>
<button class="amlocator-button -pickup"
         data-ampickup-location="idForLocation"
         data-ampickup-js="choose-store"
         title="<?= $block->escapeHtml(__('Pick up here')) ?>">
    <?= $block->escapeHtml(__('Pick up here')) ?>
</button>
